
spring:
  resources:
    static-locations: file:/Users/???/Downloads/kmongimage/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kmongJpa?useUnicode=true&serverTimezone=Asia/Seoul
    #     url: jdbc:mysql://talentmarket-springboot-webservice.cmnyyxiclarl.ap-northeast-2.rds.amazonaws.com:3306/talentmarket_springboot_webservice?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: u1234
    #     username: talentmarket
    #     password: 2938145a
  jpa:
    hibernate:
      ddl-auto: create #validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    encoding: UTF-8




