
Spring:
  profiles:
    default: local
spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kmongJpa?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: u1234

  jpa:
    hibernate:
      ddl-auto: validate #create #validate #create #validate #create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    encoding: UTF-8
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create #create #validate #create #validate #create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    encoding: UTF-8




