name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# --------------------------추가
env:
  PROJECT_NAME: KmongJpa
  BUCKET_NAME: remarket-bucket
  CODE_DEPLOY_APP_NAME: remarket-code-deploy
  DEPLOYMENT_GROUP_NAME: remarket-server
# --------------------------추가

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: /home/runner/work/KmongJpa/KmongJpa/KmongJpa/
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      

      - name: Copy Secret
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}
          OCCUPY_SECRET_DIR: ./src/main/resources
          OCCUPY_SECRET_TEST_DIR: /src/test/resources
          OCCUPY_SECRET_DIR_FILE_NAME: application.yml
        run: echo $APPLICATION_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

         
      - name: Copy Secret2
        env:
          CONFIG_SECRET: ${{ secrets.CONFIG_SECRET }}
          OCCUPY_SECRET_DIR: ./src/main/resources
          OCCUPY_SECRET_TEST_DIR: src/test/resources
          OCCUPY_SECRET_DIR_FILE_NAME: config.properties
        run: echo $CONFIG_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

      
     
      - name: Permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: ./gradlew build -x test

        
# --------------------------추가      
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
# --------------------------추가
